import { defineNuxtPlugin } from "#app";
import PrimeVue from "primevue/config";
import Button from "primevue/button";
import AutoComplete from 'primevue/autocomplete';
import ToastService from 'primevue/toastservice';
import Toast from 'primevue/toast';
import InputOtp from 'primevue/inputotp';
import MultiSelect from 'primevue/multiselect';
import InputText from 'primevue/inputtext';
import Dialog from 'primevue/dialog';
import Chip from 'primevue/chip';
import Chips from 'primevue/chips';
import Checkbox from 'primevue/checkbox';
import OrderList from 'primevue/orderlist';
import Skeleton from 'primevue/skeleton';
import Calendar from 'primevue/calendar';
import SelectButton from 'primevue/selectbutton';
import Dropdown from 'primevue/dropdown';
import Password from 'primevue/password';
import Divider from 'primevue/divider';
import InputMask from 'primevue/inputmask';
import Avatar from 'primevue/avatar';
import FileUpload from 'primevue/fileupload';
import Textarea from 'primevue/textarea';
import ScrollTop from 'primevue/scrolltop';
import Sidebar from 'primevue/sidebar';
import ProgressSpinner from 'primevue/progressspinner';
import Breadcrumb from 'primevue/breadcrumb';
import FloatLabel from 'primevue/floatlabel';
import Slider from 'primevue/slider';
import TabView from 'primevue/tabview';
import TabPanel from 'primevue/tabpanel';
import Badge from 'primevue/badge';
import InputSwitch from 'primevue/inputswitch';
import Accordion from 'primevue/accordion';
import AccordionTab from 'primevue/accordiontab';

export default defineNuxtPlugin((nuxtApp) => {
    nuxtApp.vueApp.use(PrimeVue, {ripple: true});
    nuxtApp.vueApp.use(ToastService);
    nuxtApp.vueApp.component('Toast', Toast);
    nuxtApp.vueApp.component('Button', Button);
    nuxtApp.vueApp.component('Textarea',Textarea);
    nuxtApp.vueApp.component('InputOtp', InputOtp);
    nuxtApp.vueApp.component('InputText', InputText);
    nuxtApp.vueApp.component('Dialog', Dialog);
    nuxtApp.vueApp.component('MultiSelect', MultiSelect);
    nuxtApp.vueApp.component('AutoComplete', AutoComplete);
    nuxtApp.vueApp.component('Chip', Chip);
    nuxtApp.vueApp.component('Chips', Chips);
    nuxtApp.vueApp.component('Checkbox', Checkbox);
    nuxtApp.vueApp.component('OrderList', OrderList);
    nuxtApp.vueApp.component('Skeleton', Skeleton);
    nuxtApp.vueApp.component('Calendar', Calendar);
    nuxtApp.vueApp.component('SelectButton', SelectButton);
    nuxtApp.vueApp.component('Dropdown', Dropdown);
    nuxtApp.vueApp.component('Password', Password);
    nuxtApp.vueApp.component('Divider', Divider);
    nuxtApp.vueApp.component('InputMask', InputMask);
    nuxtApp.vueApp.component('Avatar', Avatar);
    nuxtApp.vueApp.component('FileUpload', FileUpload);
    nuxtApp.vueApp.component('ScrollTop', ScrollTop);
    nuxtApp.vueApp.component('Sidebar', Sidebar);
    nuxtApp.vueApp.component('ProgressSpinner', ProgressSpinner);
    nuxtApp.vueApp.component('Breadcrumb', Breadcrumb);
    nuxtApp.vueApp.component('FloatLabel', FloatLabel);
    nuxtApp.vueApp.component('Slider', Slider);
    nuxtApp.vueApp.component('TabView', TabView);
    nuxtApp.vueApp.component('TabPanel', TabPanel);
    nuxtApp.vueApp.component('Badge', Badge);
    nuxtApp.vueApp.component('InputSwitch', InputSwitch);
    nuxtApp.vueApp.component('Accordion', Accordion);
    nuxtApp.vueApp.component('AccordionTab', AccordionTab);
});